$(document).ready(function () {indexDict['en'] = [{ "title" : "Introduction ", 
"url" : "introduction.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Introduction ", 
"snippet" : "Thank you for choosing an . The more familiar you are with your vehicle, the better control you will have on the road. We therefore strongly suggest: Read this Owner's Manual before starting off in your new ACME car. It contains important information on vehicle operation that will help you make full...", 
"body" : "Thank you for choosing an . The more familiar you are with your vehicle, the better control you will have on the road. We therefore strongly suggest: Read this Owner's Manual before starting off in your new ACME car. It contains important information on vehicle operation that will help you make full use of the technical features available in your ACME car. The manual also contains information designed to enhance operating reliability and road safety, and to contribute to maintaining the value of your ACME car. Supplementary information can be found in the additional brochures in the onboard literature. We wish you a safe and enjoyable drive. " }, 
{ "title" : "Safety ", 
"url" : "introduction/safety.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Introduction \/ Safety ", 
"snippet" : "This chapter contains information for your own safety. Please read the information and instructions carefully before driving your new car....", 
"body" : "This chapter contains information for your own safety. Please read the information and instructions carefully before driving your new car. " }, 
{ "title" : "Symbols ", 
"url" : "introduction/safety/symbols.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Introduction \/ Safety \/ Symbols ", 
"snippet" : "The following symbols are used to indicate important safety or usage information in this manual: Indicates important information, including information to avoid minor damage or misuse of your vehicle. Indicates important information to avoid serious injury or damage to your vehicle. Indicates import...", 
"body" : "The following symbols are used to indicate important safety or usage information in this manual: Indicates important information, including information to avoid minor damage or misuse of your vehicle. Indicates important information to avoid serious injury or damage to your vehicle. Indicates important information to avoid serious or fatal injury. " }, 
{ "title" : "Maintenance and repairs ", 
"url" : "introduction/safety/maintenance-and-repairs.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Introduction \/ Safety \/ Maintenance and repairs ", 
"snippet" : "Advanced technology, e.g., the use of modern materials and high-performance electronics, requires suitable maintenance and repair methods. Therefore, have this work performed only by a ACME center or a workshop that works according to ACME repair procedures with appropriately trained personnel. If t...", 
"body" : "Advanced technology, e.g., the use of modern materials and high-performance electronics, requires suitable maintenance and repair methods. Therefore, have this work performed only by a ACME center or a workshop that works according to ACME repair procedures with appropriately trained personnel. If this work is not carried out properly, there is the danger of subsequent damage and related safety hazards. " }, 
{ "title" : "Parts and accessories ", 
"url" : "introduction/safety/parts-and-accessories.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Introduction \/ Safety \/ Parts and accessories ", 
"snippet" : "For your own safety, use genuine parts and accessories approved by ACME. When you purchase accessories tested and approved by ACME and Genuine ACME Parts, you simultaneously acquire the assurance that they have been thoroughly tested by ACME to ensure optimum performance when installed on your vehic...", 
"body" : "For your own safety, use genuine parts and accessories approved by ACME. When you purchase accessories tested and approved by ACME and Genuine ACME Parts, you simultaneously acquire the assurance that they have been thoroughly tested by ACME to ensure optimum performance when installed on your vehicle. " }, 
{ "title" : "California Proposition 65 Warning ", 
"url" : "introduction/safety/california-proposition-65-warning.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Introduction \/ Safety \/ California Proposition 65 Warning ", 
"snippet" : "California laws require us to state the following warning: Engine exhaust and a wide variety of automobile components and parts, including components found in the interior furnishings in a vehicle, contain or emit chemicals known to the State of California to cause cancer and birth defects and repro...", 
"body" : "California laws require us to state the following warning: Engine exhaust and a wide variety of automobile components and parts, including components found in the interior furnishings in a vehicle, contain or emit chemicals known to the State of California to cause cancer and birth defects and reproductive harm. In addition, certain fluids contained in vehicles and certain products of component wear contain or emit chemicals known to the State of California to cause cancer and birth defects or other reproductive harm. Battery posts, terminals and related accessories contain lead and lead compounds. Wash your hands after handling. Used engine oil contains chemicals that have caused cancer in laboratory animals. Always protect your skin by washing thoroughly with soap and water. " }, 
{ "title" : "Service and Warranty ", 
"url" : "introduction/safety/service-and-warranty.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Introduction \/ Safety \/ Service and Warranty ", 
"snippet" : "We recommend that you read this publication thoroughly. Your vehicle is covered by the following warranties: New Vehicle Limited Warranty Rust Perforation Limited Warranty Federal Emissions System Defect Warranty Federal Emissions Performance Warranty California Emission Control System Limited Warra...", 
"body" : "We recommend that you read this publication thoroughly. Your vehicle is covered by the following warranties: New Vehicle Limited Warranty Rust Perforation Limited Warranty Federal Emissions System Defect Warranty Federal Emissions Performance Warranty California Emission Control System Limited Warranty Cabriolet warranty Detailed information about these warranties is listed in the \"Service and Warranty Information Booklet\". " }, 
{ "title" : "Universal Garage Door Opener ", 
"url" : "introduction/universal-garage-door-opener.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Introduction \/ Universal Garage Door Opener ", 
"snippet" : "The Universal Garage Door Opener can be used to operate up to 3 functions in remote-controlled systems, such as garage door drives or lighting systems. The Universal Garage Door Opener replaces up to 3 different handheld transmitters. To operate it, the buttons on the side of the center armrest must...", 
"body" : "The Universal Garage Door Opener can be used to operate up to 3 functions in remote-controlled systems, such as garage door drives or lighting systems. The Universal Garage Door Opener replaces up to 3 different handheld transmitters. To operate it, the buttons on the side of the center armrest must be programmed for the desired functions. Open\/close buttons Programmable buttons " }, 
{ "title" : "The Control System ", 
"url" : "the-control-system.html", 
"breadcrumbs" : "ACME Owner's Manual \/ The Control System ", 
"snippet" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies...", 
"body" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies to safety-related functions and systems. " }, 
{ "title" : "Controls ", 
"url" : "the-control-system.html#UUID-ad4fff60-e187-775d-44bd-90e3a7a6514b", 
"breadcrumbs" : "ACME Owner's Manual \/ The Control System \/ Controls ", 
"snippet" : "The system combines the functions of a multitude of switches. This makes it easy to operate all these functions from a central location and a Control Display. Control Display Controller with buttons The button can be used to open the menus directly. The controller can be used to select menu items an...", 
"body" : "The system combines the functions of a multitude of switches. This makes it easy to operate all these functions from a central location and a Control Display. Control Display Controller with buttons The button can be used to open the menus directly. The controller can be used to select menu items and create the settings. To avoid becoming distracted and posing an unnecessary hazard to your vehicle's occupants and to other road users, never attempt to use the controls or enter information unless traffic and road conditions allow this. " }, 
{ "title" : "Universal Garage Door Opener ", 
"url" : "the-control-system/universal-garage-door-opener.html", 
"breadcrumbs" : "ACME Owner's Manual \/ The Control System \/ Universal Garage Door Opener ", 
"snippet" : "The Universal Garage Door Opener can be used to operate up to 3 functions in remote-controlled systems, such as garage door drives or lighting systems. The Universal Garage Door Opener replaces up to 3 different handheld transmitters. To operate it, the buttons on the side of the center armrest must...", 
"body" : "The Universal Garage Door Opener can be used to operate up to 3 functions in remote-controlled systems, such as garage door drives or lighting systems. The Universal Garage Door Opener replaces up to 3 different handheld transmitters. To operate it, the buttons on the side of the center armrest must be programmed for the desired functions. Open\/close buttons Programmable buttons " }, 
{ "title" : "Voice Activation ", 
"url" : "the-control-system/voice-activation.html", 
"breadcrumbs" : "ACME Owner's Manual \/ The Control System \/ Voice Activation ", 
"snippet" : "To activate the voice activation: Press the voice activation button on the steering wheel. Wait for the signal. This symbol on the Control Display indicates that the voice activation system is active: Say the command. The command appears on the Control Display....", 
"body" : "To activate the voice activation: Press the voice activation button on the steering wheel. Wait for the signal. This symbol on the Control Display indicates that the voice activation system is active: Say the command. The command appears on the Control Display. " }, 
{ "title" : "Driving ", 
"url" : "driving.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Driving ", 
"snippet" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies...", 
"body" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies to safety-related functions and systems. " }, 
{ "title" : "Ignition Lock ", 
"url" : "driving/ignition-lock.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Driving \/ Ignition Lock ", 
"snippet" : "The ignition lock is located on the dashboard. If the car is equipped with Comfort Access, the remote control only needs to be inside the car to start the engine. Only in special circumstances may you need to insert it in the ignition lock....", 
"body" : "The ignition lock is located on the dashboard. If the car is equipped with Comfort Access, the remote control only needs to be inside the car to start the engine. Only in special circumstances may you need to insert it in the ignition lock. " }, 
{ "title" : "Insert the remote control ", 
"url" : "driving/ignition-lock/insert-the-remote-control.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Driving \/ Ignition Lock \/ Insert the remote control ", 
"snippet" : "Insert the remote control all the way into the ignition lock. Radio ready state is switched on. Individual electrical devices can operate....", 
"body" : "Insert the remote control all the way into the ignition lock. Radio ready state is switched on. Individual electrical devices can operate. " }, 
{ "title" : "Remove the remote control ", 
"url" : "driving/ignition-lock/remove-the-remote-control.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Driving \/ Ignition Lock \/ Remove the remote control ", 
"snippet" : "You only need to remove the remote control if your vehicle does not have Comfort Access. Do not forcibly pull the remote control out of the ignition lock as this may cause damage. Push the remote control all the way in to release the locking mechanism. Remove the remote control. The ignition is swit...", 
"body" : "You only need to remove the remote control if your vehicle does not have Comfort Access. Do not forcibly pull the remote control out of the ignition lock as this may cause damage. Push the remote control all the way in to release the locking mechanism. Remove the remote control. The ignition is switched off if it was on. " }, 
{ "title" : "Starting the Engine ", 
"url" : "driving/starting-the-engine.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Driving \/ Starting the Engine ", 
"snippet" : "Make sure your remote control is in the ignition lock, or inside the vehicle if you have Comfort Access. Depress the brake pedal. Check that all passengers are wearing seat belts. Check that rear view mirrors are properly adjusted. Press the Start\/Stop button. Avoid repeated futile attempts at start...", 
"body" : "Make sure your remote control is in the ignition lock, or inside the vehicle if you have Comfort Access. Depress the brake pedal. Check that all passengers are wearing seat belts. Check that rear view mirrors are properly adjusted. Press the Start\/Stop button. Avoid repeated futile attempts at starting the car and avoid starting the car frequently in quick succession. Otherwise, the fuel is not burned or is inadequately burned, and there is the danger of overheating and damaging the catalytic converter. Put the gear into the D position and start driving. " }, 
{ "title" : "Stopping the Engine ", 
"url" : "driving/stopping-the-engine.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Driving \/ Stopping the Engine ", 
"snippet" : "To stop the engine: With the vehicle at a standstill, press the Start\/Stop button. Set the parking brake. Remove the remote control from the ignition lock. You only need to remove the remote control if your vehicle does not have Comfort Access. Do not forcibly pull the remote control out of the igni...", 
"body" : "To stop the engine: With the vehicle at a standstill, press the Start\/Stop button. Set the parking brake. Remove the remote control from the ignition lock. You only need to remove the remote control if your vehicle does not have Comfort Access. Do not forcibly pull the remote control out of the ignition lock as this may cause damage. " }, 
{ "title" : "Interior Equipment ", 
"url" : "interior-equipment.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Interior Equipment ", 
"snippet" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies...", 
"body" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies to safety-related functions and systems. " }, 
{ "title" : "Glove Compartment ", 
"url" : "interior-equipment.html#UUID-ce7049c6-e081-d964-110f-8c4335ce92b7", 
"breadcrumbs" : "ACME Owner's Manual \/ Interior Equipment \/ Glove Compartment ", 
"snippet" : "You open and close the glove compartment with the button right above it: Push the open\/close button (A) to open the glove compartment. To close it, just press the button again. To lock the glove compartment, use the remote control....", 
"body" : "You open and close the glove compartment with the button right above it: Push the open\/close button (A) to open the glove compartment. To close it, just press the button again. To lock the glove compartment, use the remote control. " }, 
{ "title" : "Cupholders ", 
"url" : "interior-equipment.html#UUID-1a9a05b3-7da1-18eb-af2a-666cc6c2c0f7", 
"breadcrumbs" : "ACME Owner's Manual \/ Interior Equipment \/ Cupholders ", 
"snippet" : "The cupholders are located in the center armrest. Use light and shatter-proof containers and do not transport hot drinks. Otherwise, there is the increased danger of injury in an accident....", 
"body" : "The cupholders are located in the center armrest. Use light and shatter-proof containers and do not transport hot drinks. Otherwise, there is the increased danger of injury in an accident. " }, 
{ "title" : "Entertainment ", 
"url" : "entertainment.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Entertainment ", 
"snippet" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies...", 
"body" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies to safety-related functions and systems. To avoid becoming distracted and posing an unnecessary hazard to your vehicle's occupants and to other road users, never attempt to use the controls or enter information unless traffic and road conditions allow this. " }, 
{ "title" : "CD\/Multimedia ", 
"url" : "entertainment/cd-multimedia.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Entertainment \/ CD\/Multimedia ", 
"snippet" : "Play\/Pause Next track Previous track Programmable buttons To play a CD\/DVD: Insert the CD\/DVD with the printed side up. Press Play. Change track using the Next track or Previous track buttons....", 
"body" : "Play\/Pause Next track Previous track Programmable buttons To play a CD\/DVD: Insert the CD\/DVD with the printed side up. Press Play. Change track using the Next track or Previous track buttons. " }, 
{ "title" : "Apple CarPlay ", 
"url" : "entertainment/apple-carplay.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Entertainment \/ Apple CarPlay ", 
"snippet" : "informal topic content Available on all ACME models with the iMonitor system, Apple CarPlay is the best way to connect your Apple iPhone to your new ACME car. Follow this easy step-by-step guide to pair your iPhone to your ACME car with Apple CarPlay. Make sure Bluetooth, WiFi, and Siri are activate...", 
"body" : "informal topic content Available on all ACME models with the iMonitor system, Apple CarPlay is the best way to connect your Apple iPhone to your new ACME car. Follow this easy step-by-step guide to pair your iPhone to your ACME car with Apple CarPlay. Make sure Bluetooth, WiFi, and Siri are activated on your iPhone. On left side of your screen, press Communication > Mobile Devices > New Device > Phone calls and audio. The system is now discoverable from your iPhone, and may display nearby devices. On your iPhone, select your ACME car from the Bluetooth menu. The two will now begin pairing, and your iMonitor screen will confirm the pairing request. Confirm the PIN displayed on your screen and iPhone screens match, then press Yes. Select the option to connect to Apple CarPlay on your iMonitor screen. Your iPhone and ACME iMonitor system are now connected via Apple CarPlay. " }, 
{ "title" : "Technical Data ", 
"url" : "technical-data.html", 
"breadcrumbs" : "ACME Owner's Manual \/ Technical Data ", 
"snippet" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies...", 
"body" : "The sections below describe all series equipment as well as country-specific and special equipment offered for this model series. Therefore, it also describes equipment that may not be found in your vehicle, for instance due to the selected special equipment or the country version. This also applies to safety-related functions and systems. Tech data #1 Tech data #2 " }, 
{ "title" : "Dimensions ", 
"url" : "technical-data.html#UUID-e94baa8b-6a65-239b-a5a2-944bbf9ab72e", 
"breadcrumbs" : "ACME Owner's Manual \/ Technical Data \/ Dimensions ", 
"snippet" : "[Placeholder for table with reuse text and variables]...", 
"body" : "[Placeholder for table with reuse text and variables] " }, 
{ "title" : "Weights ", 
"url" : "technical-data.html#UUID-7b6178ab-67d6-188a-3dc9-75dff7628225", 
"breadcrumbs" : "ACME Owner's Manual \/ Technical Data \/ Weights ", 
"snippet" : "Weight type Unit Value Approved gross vehicle weight lbs\/kg 6,250\/2,835 Load lbs\/kg 937\/425 Approved front axle load lbs\/kg 3,020\/1,370 Approved rear axle load lbs\/kg 3,351\/1,520...", 
"body" : "Weight type Unit Value Approved gross vehicle weight lbs\/kg 6,250\/2,835 Load lbs\/kg 937\/425 Approved front axle load lbs\/kg 3,020\/1,370 Approved rear axle load lbs\/kg 3,351\/1,520 " }
]
$(document).trigger('search.ready');
});